// Freeze the proposed FUTURE-facing v1 parameter set from the 'all' fold
// (every cohort bout, 2015-2026), with full provenance, into
// src/engine/params_fitted_v1.mjs. Run ONLY after the walk-forward
// evaluation is complete and accepted; it never alters historical scoring
// (the evaluator refuses this fit, see guard.mjs).
import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { CACHE, buildCohort, roundObservations } from './dataset.mjs';
import { sha256Hex } from '../src/engine/sha256.mjs';
import { canonicalJson } from '../src/engine/canonical.mjs';

const FIT_VERSION = 'pbe-sim-fit-v1';
const p = JSON.parse(fs.readFileSync(path.join(CACHE, 'params_fold_all.json'), 'utf8'));
if (!/^all/.test(p.provenance?.fold || '')) throw new Error('freeze expects params_fold_all.json (source fold = all)');

// Dataset hash: canonical JSON of the cohort (ids, dates, truth) and every per-round observation the fit consumed.
const { cohort } = buildCohort();
const hasher = [];
for (const c of cohort) { const { obs } = roundObservations(c); hasher.push(canonicalJson({ c: [c.bout_id, c.event_date, c.method, c.end_round, c.end_time, c.winner_id], o: obs.map((o) => [o.side, o.round, o.L, o.x, o.y]) })); }
const datasetSha = sha256Hex(hasher.join('\n'));
// Code identity: the Phase 3 branch base (the fit code lives in the commit that contains this file, which cannot know its
// own SHA). Pass --code-sha to pin explicitly; otherwise the branch base is resolved from git.
const argv = process.argv.slice(2);
const argSha = argv.indexOf('--code-sha') >= 0 ? argv[argv.indexOf('--code-sha') + 1] : null;
let codeSha = argSha || 'unknown';
if (!argSha) { try { codeSha = execSync('git rev-parse fight-simulator-phase3', { cwd: path.resolve(CACHE, '..', '..'), encoding: 'utf8' }).trim(); } catch {} }

const provenance = {
  fit_version: FIT_VERSION,
  source_fold: 'all',
  training_window: p.provenance.training_window,
  training_bouts: p.provenance.training_bouts,
  training_observations: p.provenance.training_observations,
  dataset_sha256: datasetSha,
  code_sha: codeSha,
  code_sha_meaning: 'fight-simulator-phase3 branch base; the fitting code and this file are committed on that branch',
  objective: p.provenance.objective,
  hazard_calibration: p.provenance.hazard_calibration,
  components: p.provenance.components,
  finish_time_samples: p.provenance.finish_time_samples,
  generated_at: new Date().toISOString(),
  evaluation: 'docs/FIGHT_SIMULATOR_PHASE3.md (walk-forward 2016-2026; this all-data fit never scored a historical bout)',
};
const out = path.resolve(CACHE, '..', '..', 'src', 'engine', 'params_fitted_v1.mjs');
const models = {};
for (const [k, v] of Object.entries(p.models)) models[k] = { ...v, provenance: `${FIT_VERSION}:all-2015-2026` };
const body = `// GENERATED by phase3/freeze.mjs. Do not edit by hand.
// Proposed pbe-fight-simulator v1.0 fitted component models: every cohort bout 2015-2026, walk-forward validated in
// docs/FIGHT_SIMULATOR_PHASE3.md. The engine spec hash covers these values, so any change is a new engine spec.
export const FITTED_MODELS_V1 = Object.freeze(${JSON.stringify(models, null, 2)});
export const FITTED_FINISH_TIME_V1 = Object.freeze({ finish_time_shape: ${p.finish_time_shape}, finish_time_shape_kd: ${p.finish_time_shape_kd} });
export const FITTED_PROVENANCE_V1 = Object.freeze(${JSON.stringify(provenance, null, 2)});
`;
fs.writeFileSync(out, body);
fs.writeFileSync(path.join(CACHE, 'frozen_v1_provenance.json'), JSON.stringify(provenance, null, 1));
console.log(JSON.stringify({ wrote: out, training_bouts: provenance.training_bouts, dataset_sha256: datasetSha, code_sha: codeSha, generated_at: provenance.generated_at }, null, 1));
