/* Generated by scripts/tuf/build_details_index.mjs — do not edit by hand.
 *
 * One static import per season episode file (scripts/tuf/build_episodes.mjs). */
import tuf1 from "./episodes/tuf-1.json";
import tuf2 from "./episodes/tuf-2.json";
import tuf3 from "./episodes/tuf-3.json";
import tuf4 from "./episodes/tuf-4.json";
import tuf5 from "./episodes/tuf-5.json";
import tuf6 from "./episodes/tuf-6.json";
import tuf7 from "./episodes/tuf-7.json";
import tuf8 from "./episodes/tuf-8.json";
import tuf9 from "./episodes/tuf-9.json";
import tuf10 from "./episodes/tuf-10.json";
import tuf11 from "./episodes/tuf-11.json";
import tuf12 from "./episodes/tuf-12.json";
import tuf13 from "./episodes/tuf-13.json";
import tuf14 from "./episodes/tuf-14.json";
import tuf15 from "./episodes/tuf-15.json";
import tuf16 from "./episodes/tuf-16.json";
import tuf17 from "./episodes/tuf-17.json";
import tuf18 from "./episodes/tuf-18.json";
import tuf19 from "./episodes/tuf-19.json";
import tuf20 from "./episodes/tuf-20.json";
import tuf21 from "./episodes/tuf-21.json";
import tuf22 from "./episodes/tuf-22.json";
import tuf23 from "./episodes/tuf-23.json";
import tuf24 from "./episodes/tuf-24.json";
import tuf25 from "./episodes/tuf-25.json";
import tuf26 from "./episodes/tuf-26.json";
import tuf27 from "./episodes/tuf-27.json";
import tuf28 from "./episodes/tuf-28.json";
import tuf29 from "./episodes/tuf-29.json";
import tuf30 from "./episodes/tuf-30.json";
import tuf31 from "./episodes/tuf-31.json";
import tuf32 from "./episodes/tuf-32.json";
import tuf33 from "./episodes/tuf-33.json";
import tuf34 from "./episodes/tuf-34.json";
import tufBrazil1 from "./episodes/tuf-brazil-1.json";
import tufBrazil2 from "./episodes/tuf-brazil-2.json";
import tufBrazil3 from "./episodes/tuf-brazil-3.json";
import tufBrazil4 from "./episodes/tuf-brazil-4.json";
import tufLatam1 from "./episodes/tuf-latam-1.json";
import tufLatam2 from "./episodes/tuf-latam-2.json";
import tufLatam3 from "./episodes/tuf-latam-3.json";
import tufNations1 from "./episodes/tuf-nations-1.json";
import tufSmashes1 from "./episodes/tuf-smashes-1.json";

export const TUF_EPISODES: Record<string, unknown> = {
  "tuf-1": tuf1,
  "tuf-2": tuf2,
  "tuf-3": tuf3,
  "tuf-4": tuf4,
  "tuf-5": tuf5,
  "tuf-6": tuf6,
  "tuf-7": tuf7,
  "tuf-8": tuf8,
  "tuf-9": tuf9,
  "tuf-10": tuf10,
  "tuf-11": tuf11,
  "tuf-12": tuf12,
  "tuf-13": tuf13,
  "tuf-14": tuf14,
  "tuf-15": tuf15,
  "tuf-16": tuf16,
  "tuf-17": tuf17,
  "tuf-18": tuf18,
  "tuf-19": tuf19,
  "tuf-20": tuf20,
  "tuf-21": tuf21,
  "tuf-22": tuf22,
  "tuf-23": tuf23,
  "tuf-24": tuf24,
  "tuf-25": tuf25,
  "tuf-26": tuf26,
  "tuf-27": tuf27,
  "tuf-28": tuf28,
  "tuf-29": tuf29,
  "tuf-30": tuf30,
  "tuf-31": tuf31,
  "tuf-32": tuf32,
  "tuf-33": tuf33,
  "tuf-34": tuf34,
  "tuf-brazil-1": tufBrazil1,
  "tuf-brazil-2": tufBrazil2,
  "tuf-brazil-3": tufBrazil3,
  "tuf-brazil-4": tufBrazil4,
  "tuf-latam-1": tufLatam1,
  "tuf-latam-2": tufLatam2,
  "tuf-latam-3": tufLatam3,
  "tuf-nations-1": tufNations1,
  "tuf-smashes-1": tufSmashes1,
};
