#!/usr/bin/env node
// Regenerate the season-detail import map.
//
//   node scripts/tuf/build_details_index.mjs
//
// Next bundles what it can see statically, so the detail files have to be
// imported by name rather than read from disk at request time. That was a
// hand-maintained list of four, which is fine for four and a standing bug for
// forty-four: a season whose file exists but whose import was forgotten
// renders as metadata-only and looks like missing data rather than a missed
// line. The list is generated from the directory instead.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const DIR = path.join(ROOT, 'web', 'data', 'tuf', 'seasons');
const OUT = path.join(ROOT, 'web', 'data', 'tuf', 'details.generated.ts');

const slugs = fs
  .readdirSync(DIR)
  .filter((f) => f.endsWith('.json'))
  .map((f) => f.replace(/\.json$/, ''))
  .sort((a, b) => a.localeCompare(b, 'en', { numeric: true }));

const ident = (slug) => slug.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase()).replace(/^(\d)/, '_$1');

const body = `/* Generated by scripts/tuf/build_details_index.mjs — do not edit by hand.
 *
 * One static import per season detail file, so the bundler can see them all.
 * Regenerate after adding a season; the archive tests fail if a season claims
 * bracket coverage and this map does not carry it. */
${slugs.map((s) => `import ${ident(s)} from "./seasons/${s}.json";`).join('\n')}

export const TUF_DETAILS: Record<string, unknown> = {
${slugs.map((s) => `  ${JSON.stringify(s)}: ${ident(s)},`).join('\n')}
};
`;

fs.writeFileSync(OUT, body);
console.log(`${slugs.length} season detail file(s) -> ${path.relative(ROOT, OUT)}`);

/* The episode layer (scripts/tuf/build_episodes.mjs), bundled the same way
 * and for the same reason. */
const EP_DIR = path.join(ROOT, 'web', 'data', 'tuf', 'episodes');
const EP_OUT = path.join(ROOT, 'web', 'data', 'tuf', 'episodes.generated.ts');
const epSlugs = fs.existsSync(EP_DIR)
  ? fs.readdirSync(EP_DIR).filter((f) => f.endsWith('.json')).map((f) => f.replace(/\.json$/, '')).sort((a, b) => a.localeCompare(b, 'en', { numeric: true }))
  : [];
fs.writeFileSync(EP_OUT, `/* Generated by scripts/tuf/build_details_index.mjs — do not edit by hand.
 *
 * One static import per season episode file (scripts/tuf/build_episodes.mjs). */
${epSlugs.map((s) => `import ${ident(s)} from "./episodes/${s}.json";`).join('\n')}

export const TUF_EPISODES: Record<string, unknown> = {
${epSlugs.map((s) => `  ${JSON.stringify(s)}: ${ident(s)},`).join('\n')}
};
`);
console.log(`${epSlugs.length} season episode file(s) -> ${path.relative(ROOT, EP_OUT)}`);
