// Shared plumbing for the PBE Fight Model v1 pipeline.
//
// Read-only against production. Nothing in scripts/model/ writes a row to the
// database; the model's write path is the migration in migrations/010, applied
// deliberately and separately. Every reader here is a GET.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

export function loadEnv() {
  const p = path.join(ROOT, '.env');
  if (!fs.existsSync(p)) return;
  for (const line of fs.readFileSync(p, 'utf8').split(/\r?\n/)) {
    // The file is written by Windows tooling and can carry a BOM on line one.
    const m = line.match(/^\s*\ufeff?([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (m && process.env[m[1]] === undefined) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
}

/** Where the read-only extract and every derived artifact live.
 *
 *  Set PBE_MODEL_CACHE to keep it off the repo volume. The extract is roughly
 *  85 MB and is pure derived state - it is regenerated by extract_dataset.mjs
 *  and never committed. */
export function cacheDir() {
  const d = process.env.PBE_MODEL_CACHE || path.join(ROOT, '.cache', 'model');
  fs.mkdirSync(d, { recursive: true });
  return d;
}

export function rest() {
  loadEnv();
  const url = (process.env.SUPABASE_URL || '').replace(/\/$/, '');
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY || '';
  if (!url || !key) throw new Error('SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY missing');
  const headers = { apikey: key, Authorization: `Bearer ${key}`, Accept: 'application/json' };

  // Deterministic pagination. PostgREST caps a page, so every read is ordered
  // by a unique key and walked to exhaustion; a read that silently returned
  // only the first page would poison every downstream number.
  async function page(table, query, offset, limit) {
    const q = query.startsWith('?') ? query : `?${query}`;
    const res = await fetch(`${url}/rest/v1/${table}${q}&limit=${limit}&offset=${offset}`, { headers });
    if (!res.ok) throw new Error(`${table} -> HTTP ${res.status}: ${(await res.text()).slice(0, 300)}`);
    return res.json();
  }

  return {
    async selectAll(table, query, { limit = 1000, onPage } = {}) {
      const out = [];
      for (let offset = 0; ; offset += limit) {
        const rows = await page(table, query, offset, limit);
        out.push(...rows);
        if (onPage) onPage(out.length);
        if (rows.length < limit) break;
      }
      return out;
    },
    async count(table, query = 'select=*') {
      const q = query.startsWith('?') ? query : `?${query}`;
      const res = await fetch(`${url}/rest/v1/${table}${q}`, {
        headers: { ...headers, Prefer: 'count=exact', Range: '0-0', 'Range-Unit': 'items' },
      });
      const cr = res.headers.get('content-range') || '';
      const n = Number(cr.split('/')[1]);
      return Number.isFinite(n) ? n : null;
    },
  };
}

export const readJsonl = (file) =>
  fs.readFileSync(file, 'utf8').split('\n').filter(Boolean).map((l) => JSON.parse(l));

export const writeJsonl = (file, rows) => {
  fs.writeFileSync(file, rows.map((r) => JSON.stringify(r)).join('\n') + (rows.length ? '\n' : ''));
  return rows.length;
};

export const num = (v) => {
  if (v === null || v === undefined || v === '') return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
};

/** Whole days between two YYYY-MM-DD dates. UTC so a DST boundary cannot shift a fight by a day. */
export const daysBetween = (a, b) =>
  Math.round((Date.parse(`${b}T00:00:00Z`) - Date.parse(`${a}T00:00:00Z`)) / 86400000);

export const round = (v, p = 6) => (v == null || !Number.isFinite(v) ? null : Math.round(v * 10 ** p) / 10 ** p);
