#!/usr/bin/env node
// Renders docs/model/BACKTEST_v1.md from the backtest artifacts.
//
//   node scripts/model/report.mjs
//
// The report is generated rather than written, because a number typed into a
// document by hand is a number that will eventually disagree with the pipeline
// that produced it, and the disagreement will be discovered by a reader rather
// than by us.

import fs from 'node:fs';
import path from 'node:path';
import { cacheDir, ROOT } from './common.mjs';

const pct = (v, dp = 2) => (v == null ? '—' : `${(v * 100).toFixed(dp)}%`);
const f = (v, dp = 5) => (v == null ? '—' : Number(v).toFixed(dp));
const n = (v) => (v == null ? '—' : Number(v).toLocaleString('en-US'));

const cache = cacheDir();
const s = JSON.parse(fs.readFileSync(path.join(cache, 'backtest_v1.json'), 'utf8'));
const audit = JSON.parse(fs.readFileSync(path.join(cache, 'leakage_audit.json'), 'utf8'));
const artifact = JSON.parse(fs.readFileSync(path.join(ROOT, 'web', 'lib', 'generated', 'model-v1.json'), 'utf8'));

const h = s.headline;
const L = [];
const w = (...lines) => L.push(...lines);

w(`# PBE Fight Model v1 — backtest results`, '');
w(`> Generated by \`scripts/model/report.mjs\`. Every number below comes from`,
  `> \`.cache/model/backtest_v1.json\` and \`leakage_audit.json\`; none is typed by hand.`, '');
w(`| | |`, `|---|---|`);
w(`| Model version | \`${s.model_version}\` |`);
w(`| Feature version | \`${s.feature_version}\` |`);
w(`| Spec hash | \`${artifact.model.spec_sha256}\` |`);
w(`| Features | ${artifact.model.feature_count} |`);
w(`| Algorithm | ${artifact.model.algorithm} |`);
w(`| Validation | ${s.protocol.validation} |`);
w(`| Folds | ${s.protocol.folds} |`);
w(`| Out-of-sample bouts | ${n(s.out_of_sample.n)} |`);
w(`| Period scored | ${s.out_of_sample.first_event} → ${s.out_of_sample.last_event} |`);
w(`| Base rate (canonical corner one) | ${pct(s.out_of_sample.base_rate, 2)} |`);
w(`| Generated | ${s.generated_at} |`, '');

w(`## Headline: does v1 provide real signal?`, '');
w(`Yes, modestly and consistently, and without a sportsbook price anywhere in the inputs.`, '');
w(`| Benchmark | Fights | Brier | Log loss | Accuracy | AUC |`, `|---|--:|--:|--:|--:|--:|`);
w(`| **PBE Fight Model v1** | ${n(h.model.n)} | **${f(h.model.brier)}** | **${f(h.model.log_loss)}** | **${pct(h.model.accuracy)}** | **${f(h.model.auc, 4)}** |`);
w(`| 50/50 baseline | ${n(h.coin.n)} | ${f(h.coin.brier)} | ${f(h.coin.log_loss)} | ${pct(h.coin.accuracy)} | — |`);
w(`| Historical win-rate baseline | ${n(h.winrate.n)} | ${f(h.winrate.brier)} | ${f(h.winrate.log_loss)} | ${pct(h.winrate.accuracy)} | ${f(h.winrate.auc, 4)} |`);
w(h.market.n
  ? `| Market implied (de-vigged) | ${n(h.market.n)} | ${f(h.market.brier)} | ${f(h.market.log_loss)} | ${pct(h.market.accuracy)} | ${f(h.market.auc, 4)} |`
  : `| Market implied (de-vigged) | 0 | — | — | — | — |`);
w('');
w(`- **Brier skill vs the coin: ${pct(h.model_vs_coin_brier_skill)}**`);
w(`- **Brier skill vs the win-rate baseline: ${pct(h.model_vs_winrate_brier_skill)}**`);
w(`- Log loss improvement over the win-rate baseline: ${f(h.model_vs_winrate_logloss_delta, 5)} nats/fight`);
w(`- Hit rate ${pct(s.out_of_sample.hits / s.out_of_sample.n)} (${n(s.out_of_sample.hits)}/${n(s.out_of_sample.n)}), 95% CI [${pct(s.out_of_sample.hit_rate_ci95.lo)}, ${pct(s.out_of_sample.hit_rate_ci95.hi)}]`);
w(`- Calibration: ECE ${f(h.model.calibration.ece, 4)}, slope ${f(h.model.calibration.slope, 3)}`, '');
if (!h.market.n) {
  w(`**Market comparison is empty and stays empty.** ${h.market.note}`, '');
}

w(`## Calibration`, '');
w(`Both corners of a bout are the same prediction stated two ways, so every row is`,
  `folded onto the side the model picked: confidence is max(p, 1−p) and a hit is that`,
  `pick winning. Binning raw p would double count and produce a mirror-symmetric plot`,
  `that says nothing.`, '');
w(`| Confidence | Fights | Claimed | Observed | Difference |`, `|---|--:|--:|--:|--:|`);
for (const b of h.model.calibration.bins.filter((x) => x.n > 0)) {
  w(`| ${(b.lo * 100).toFixed(0)}–${(b.hi * 100).toFixed(0)}% | ${n(b.n)} | ${pct(b.predicted)} | ${pct(b.observed)} | ${((b.observed - b.predicted) * 100).toFixed(2)} pts |`);
}
w('');

w(`## By confidence band`, '');
w(`| Band | Fights | Claimed | Hit rate | Brier |`, `|---|--:|--:|--:|--:|`);
for (const b of s.by_confidence_band.filter((x) => x.n > 0)) {
  w(`| ${b.band}% | ${n(b.n)} | ${pct(b.mean_confidence)} | ${pct(b.hit_rate)} | ${f(b.brier)} |`);
}
w('');

w(`## By division`, '');
w(`| Division | Fights | Brier | Log loss | Accuracy | AUC |`, `|---|--:|--:|--:|--:|--:|`);
for (const d of s.by_division) {
  w(`| ${d.key} | ${n(d.n)} | ${f(d.brier)} | ${f(d.log_loss)} | ${pct(d.accuracy)} | ${f(d.auc, 4)} |`);
}
w('');

w(`## By evidence available`, '');
w(`The honest limit of v1. When one corner has never fought inside the promotion,`,
  `there is almost nothing to read beyond age, reach and stance, and the model says so`,
  `by producing probabilities near 50% rather than by manufacturing confidence.`, '');
w(`| Evidence | Fights | Brier | Accuracy | AUC |`, `|---|--:|--:|--:|--:|`);
for (const d of [...s.by_sample_quality].sort((a, b) => a.key.localeCompare(b.key))) {
  w(`| ${d.key.replace(/^[a-d]\. /, '')} | ${n(d.n)} | ${f(d.brier)} | ${pct(d.accuracy)} | ${f(d.auc, 4)} |`);
}
w('');

w(`## Fold by fold`, '');
w(`Expanding training window, refit from scratch each year. The ridge penalty is`,
  `selected on an inner chronological split of the training window, never on the year`,
  `being scored.`, '');
w(`| Year | Trained on | Scored | λ | Brier | Log loss | Accuracy | AUC |`, `|---|--:|--:|--:|--:|--:|--:|--:|`);
for (const fold of s.folds.filter((x) => !x.skipped)) {
  w(`| ${fold.year} | ${n(fold.train_n)} | ${n(fold.test_n)} | ${fold.lambda} | ${f(fold.metrics.brier)} | ${f(fold.metrics.log_loss)} | ${pct(fold.metrics.accuracy)} | ${f(fold.metrics.auc, 4)} |`);
}
w('');
const beat = s.folds.filter((x) => !x.skipped && x.metrics.brier < 0.25).length;
const total = s.folds.filter((x) => !x.skipped).length;
w(`${beat} of ${total} folds beat the coin on Brier.`, '');

w(`## Coefficients`, '');
w(`Mean across folds, largest first. The expected sign is the fight-sense prior`,
  `recorded in \`feature_spec.mjs\` before fitting. Where the learned sign contradicts`,
  `it, the row is flagged and left alone — the flag is the finding.`, '');
w(`| Feature | Family | Source | Mean coefficient | Sign stability | Expected | Contradicts prior |`, `|---|---|---|--:|--:|:-:|:-:|`);
for (const c of s.coefficient_signs) {
  w(`| \`${c.key}\` | ${c.family} | ${c.source.replace(/_/g, ' ')} | ${f(c.mean_coefficient, 4)} | ${pct(c.sign_stability, 0)} | ${c.expected_sign} | ${c.contradicts_prior ? '**yes**' : ''} |`);
}
w('');
const contradicting = s.coefficient_signs.filter((c) => c.contradicts_prior);
if (contradicting.length) {
  w(`${contradicting.length} coefficient${contradicting.length === 1 ? '' : 's'} learned the opposite sign to the prior:`,
    contradicting.map((c) => `\`${c.key}\``).join(', ') + '.',
    `These are almost certainly collinearity artifacts — a knockdown rate sitting`,
    `beside a strike differential and a finish rate has little independent variance`,
    `left to explain, and ridge distributes what remains without regard for how a`,
    `human would attribute it. They are reported rather than corrected: pinning a`,
    `sign to match intuition would be fitting the report, not the fights.`, '');
}

w(`## Leakage audit`, '');
w(`All six checks passed on this build. Detail in \`docs/model/LEAKAGE.md\`.`, '');
w(`| Check | Result |`, `|---|---|`);
for (const c of audit.checks) w(`| ${c.name} | ${c.pass ? 'PASS' : '**FAIL**'} |`);
w('');
const trunc = audit.checks.find((c) => c.name === 'truncation');
const perm = audit.checks.find((c) => c.name === 'permutation');
const prov = audit.checks.find((c) => c.name === 'snapshot provenance');
w(`- Truncation: ${n(trunc.bouts_rebuilt_with_all_later_data_deleted)} bouts rebuilt with every row dated on or after them deleted; ${trunc.vectors_that_changed} feature vectors changed.`);
w(`- Permutation: shuffling the training labels dropped Brier skill from ${pct(perm.real_brier_skill_vs_coin)} to ${pct(perm.permuted_label_brier_skill_vs_coin)}.`);
w(`- Snapshot provenance: ${prov.snapshot_record_vs_independent_ladder}; closest bout inside any selected snapshot was ${prov.closest_included_bout_days_before_event} days before the event it predicted.`, '');

w(`## Reproducing this`, '');
w('```bash',
  'node scripts/model/extract_dataset.mjs   # read-only pull from Supabase',
  'node scripts/model/build_features.mjs    # as-of feature assembly + audit counters',
  'node scripts/model/backtest.mjs          # walk-forward folds',
  'node scripts/model/leakage_audit.mjs     # six independent leakage checks',
  'node scripts/model/train_release.mjs     # release artifact for the web app',
  'node scripts/model/report.mjs            # this document',
  'node --test scripts/model/model.test.mjs # unit and invariant tests',
  '```', '');
w(`Feature assembly is deterministic: \`model.test.mjs\` asserts that rebuilding the`,
  `dataset from the same extract is byte-identical, so a changed number here means a`,
  `changed input or a changed definition, never a changed run.`, '');

const out = path.join(ROOT, 'docs', 'model', 'BACKTEST_v1.md');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, L.join('\n') + '\n');
console.log(`-> ${out} (${L.length} lines)`);
