-- tuf-2 contestants — attach ESPN athlete ids, 2026-09-13.
--
-- Approved for exactly these 10 fighters. Generated by
-- scripts/reconcile/tuf_espn_athlete_ids.mjs from the plan in
-- scripts/reconcile/evidence/tuf2_espn_athlete_ids.2026-09-13.json (sha256 f71b6f3f194a10016a7b9c9bdff1cb1807157e49859a891d0a3acbf0f42b2cb1).
--
-- Each mapping is anchored to one exact bout: the fighter's bout on our finale
-- event 409b765d-29b1-45c4-a9ef-ee234d350af0 reproduced by one ESPN competition on ESPN event 400254173
-- (winner/loser role, round and both names agree). Nothing is merged, no DOB is
-- written to ufc_fighters, no UFC Stats id changes. Where ESPN or a commission
-- record prints a different DOB, every value is kept in the audit evidence.
--
-- FAIL CLOSED: exact pre-state per row; any planned ESPN id already held by any
-- canonical fighter or combat ESPN identity aborts; every other row in the
-- touched tables is fingerprinted and must be identical after; touched fighters
-- may change only espn_athlete_id and updated_at.

begin;

do $attach$
declare
  PLAN_ID constant text := 'tuf2-espn-athlete-ids-2026-09-13';
  ESPN_SOURCE constant uuid := 'cd71b196-8197-4df4-a806-26a78678d04b';
  OUR_EVENT constant uuid := '409b765d-29b1-45c4-a9ef-ee234d350af0';
  plan_rows jsonb := '[
    {"fighter_id":"046fbca6-d803-4bc8-a3c9-d2d45144fc5e","combat_fighter_id":"cc4b50cb-2528-4ec1-a69f-abaa78b66d4a","name":"Joe Stevenson","ufcstats_id":"79899ecf62020f6d","espn":"2335672","espn_name":"Joe Stevenson","espn_dob":"1982-06-15","canonical_dob":"1982-06-15","commission_dob":"1982-06-15","bout_id":"1027f33c-bd93-46f3-a424-277a6927c822","opponent_id":"e76e4a06-7d74-4ecb-a0dc-7d07234e3f64","role":"winner","competition":"152155"},
    {"fighter_id":"1f85c086-ece4-46fd-9cb0-cd991a3caaee","combat_fighter_id":"d4184794-217c-48f8-866a-c58e1e45708d","name":"Joshua Burkman","ufcstats_id":"6da99156486ed6c2","espn":"2354104","espn_name":"Joshua Burkman","espn_dob":"1980-04-10","canonical_dob":"1980-04-10","commission_dob":"1980-04-10","bout_id":"e1f04fc8-c64f-467f-b511-a377562d6caf","opponent_id":"aec0fc0e-6465-43bf-a8f8-958b6e75f37f","role":"winner","competition":"156030"},
    {"fighter_id":"492896ac-287f-44c2-93d1-ea86443c9b1a","combat_fighter_id":"6fe206f8-115f-46fa-8b72-f914d9667f94","name":"Brad Imes","ufcstats_id":"4908c5ee68a50ee5","espn":"2335606","espn_name":"Brad Imes","espn_dob":"1977-03-16","canonical_dob":"1977-03-13","commission_dob":"1977-03-16","bout_id":"efdfe676-6d25-4f2e-b8fe-e31bb368e99b","opponent_id":"b65310ab-e8fa-40ab-875a-aaa383ece4e5","role":"loser","competition":"151877"},
    {"fighter_id":"6514832c-6208-44d9-a8e0-b81f9853a196","combat_fighter_id":"6ad20097-1057-4273-9582-8de2916e8012","name":"Kerry Schall","ufcstats_id":"030f08370fd1c2bb","espn":"2354537","espn_name":"Kerry Schall","espn_dob":"1971-08-09","canonical_dob":"1971-08-09","commission_dob":null,"bout_id":"e47b0998-c51a-4ae9-a79f-454c30046313","opponent_id":"fb171a51-59a5-4648-8279-76dbfdd1a83a","role":"loser","competition":"152433"},
    {"fighter_id":"7b2bb20e-a01d-47b7-94d1-10460104487a","combat_fighter_id":"400f4b5c-646e-409d-9f42-5f79907530eb","name":"Melvin Guillard","ufcstats_id":"ccd1299e0345e0ce","espn":"2335800","espn_name":"Melvin Guillard","espn_dob":"1983-03-30","canonical_dob":"1983-03-30","commission_dob":null,"bout_id":"c7f797d7-b5da-40ce-87f9-1c1eb2a2f6fa","opponent_id":"8e03c8d3-5971-4c46-a77d-c18651e9061a","role":"winner","competition":"152437"},
    {"fighter_id":"8e03c8d3-5971-4c46-a77d-c18651e9061a","combat_fighter_id":"50204430-bb7b-495d-87cd-0b1b37a0751e","name":"Marcus Davis","ufcstats_id":"b7d524c77c27389b","espn":"2335804","espn_name":"Marcus Davis","espn_dob":"1973-08-24","canonical_dob":"1973-08-24","commission_dob":"1973-08-24","bout_id":"c7f797d7-b5da-40ce-87f9-1c1eb2a2f6fa","opponent_id":"7b2bb20e-a01d-47b7-94d1-10460104487a","role":"loser","competition":"152437"},
    {"fighter_id":"aec0fc0e-6465-43bf-a8f8-958b6e75f37f","combat_fighter_id":"8b5acff6-b425-4012-a0ff-cddff5267f99","name":"Sammy Morgan","ufcstats_id":"2067a177a2842fbf","espn":"2335817","espn_name":"Sammy Morgan","espn_dob":"1981-09-28","canonical_dob":"1981-09-28","commission_dob":"1981-09-28","bout_id":"e1f04fc8-c64f-467f-b511-a377562d6caf","opponent_id":"1f85c086-ece4-46fd-9cb0-cd991a3caaee","role":"loser","competition":"156030"},
    {"fighter_id":"b65310ab-e8fa-40ab-875a-aaa383ece4e5","combat_fighter_id":"aeb9dbdb-7f06-4b67-8eb6-ef3766e9534e","name":"Rashad Evans","ufcstats_id":"ee779c43a8926d52","espn":"2335465","espn_name":"Rashad Evans","espn_dob":"1979-09-25","canonical_dob":"1979-09-25","commission_dob":"1979-09-25","bout_id":"efdfe676-6d25-4f2e-b8fe-e31bb368e99b","opponent_id":"492896ac-287f-44c2-93d1-ea86443c9b1a","role":"winner","competition":"151877"},
    {"fighter_id":"e76e4a06-7d74-4ecb-a0dc-7d07234e3f64","combat_fighter_id":"403b03e9-c3a7-4ed1-92d9-a88c0fdd4edc","name":"Luke Cummo","ufcstats_id":"93ce4ac89e3d7652","espn":"2335799","espn_name":"Luke Cummo","espn_dob":"1980-04-27","canonical_dob":"1980-04-27","commission_dob":"1980-04-27","bout_id":"1027f33c-bd93-46f3-a424-277a6927c822","opponent_id":"046fbca6-d803-4bc8-a3c9-d2d45144fc5e","role":"loser","competition":"152155"},
    {"fighter_id":"fb171a51-59a5-4648-8279-76dbfdd1a83a","combat_fighter_id":"ea23ec42-4f30-420a-9f88-9bb8d21d04e5","name":"Keith Jardine","ufcstats_id":"b9d0fd83bb8a147a","espn":"2335469","espn_name":"Keith Jardine","espn_dob":"1975-10-31","canonical_dob":"1975-10-31","commission_dob":"1975-10-31","bout_id":"e47b0998-c51a-4ae9-a79f-454c30046313","opponent_id":"6514832c-6208-44d9-a8e0-b81f9853a196","role":"winner","competition":"152433"}
  ]'::jsonb;
  touched uuid[];
  p jsonb; n bigint; fp_before jsonb; fp_after jsonb; k text; before_row jsonb; after_row jsonb; new_ids uuid[] := '{}'; new_id uuid;
begin
  select array_agg((x->>'fighter_id')::uuid) into touched from jsonb_array_elements(plan_rows) x;
  if jsonb_array_length(plan_rows) <> 10 or (select count(distinct x->>'espn') from jsonb_array_elements(plan_rows) x) <> 10
     or (select count(distinct x->>'fighter_id') from jsonb_array_elements(plan_rows) x) <> 10 then
    raise exception 'plan: expected 10 distinct fighters and 10 distinct ESPN ids'; end if;
  select count(*) into n from public.ufc_fighters where espn_athlete_id in (select x->>'espn' from jsonb_array_elements(plan_rows) x);
  if n <> 0 then raise exception 'collision: % canonical fighter(s) already hold a planned ESPN id', n; end if;
  select count(*) into n from public.combat_fighter_identities where source_id = ESPN_SOURCE and external_id in (select x->>'espn' from jsonb_array_elements(plan_rows) x);
  if n <> 0 then raise exception 'collision: % combat ESPN identity row(s) already hold a planned ESPN id', n; end if;

  select jsonb_build_object(
    'ufc_fighters',              (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_fighters t where t.id <> all(touched)),
    'ufc_fighters_touched_rest', (select jsonb_build_array(count(*), md5(coalesce(string_agg((to_jsonb(t) - 'espn_athlete_id' - 'updated_at')::text, '|' order by t.id), ''))) from public.ufc_fighters t where t.id = any(touched)),
    'ufc_bouts',                 (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_bouts t),
    'ufc_bout_results',          (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.bout_id), ''))) from public.ufc_bout_results t),
    'ufc_fighter_aliases',       (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_fighter_aliases t),
    'ufc_images',                (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_images t),
    'ufc_image_candidates',      (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_image_candidates t),
    'combat_fighters',           (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.combat_fighters t),
    'combat_fighter_identities', (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.combat_fighter_identities t ),
    'ufc_identity_reconciliations', (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_identity_reconciliations t )
  ) into fp_before;

  for p in select * from jsonb_array_elements(plan_rows) loop
    if not exists (select 1 from public.ufc_fighters where id = (p->>'fighter_id')::uuid and name = p->>'name'
                     and ufcstats_id = p->>'ufcstats_id' and espn_athlete_id is null
                     and dob is not distinct from (p->>'canonical_dob')::date) then
      raise exception 'drift: % is not the planned canonical row (name, UFC Stats id, DOB, no ESPN id)', p->>'name'; end if;
    if not exists (select 1 from public.ufc_bouts b join public.ufc_bout_results r on r.bout_id = b.id
                     where b.id = (p->>'bout_id')::uuid and b.event_id = OUR_EVENT
                       and array[b.fighter_a_id, b.fighter_b_id] @> array[(p->>'fighter_id')::uuid, (p->>'opponent_id')::uuid]
                       and ((p->>'role' = 'winner' and r.winner_id = (p->>'fighter_id')::uuid) or (p->>'role' = 'loser' and r.winner_id = (p->>'opponent_id')::uuid))) then
      raise exception 'drift: % bout % is not the planned finale bout, opponent and result', p->>'name', p->>'bout_id'; end if;
    if (select count(*) from public.combat_fighters where id = (p->>'combat_fighter_id')::uuid and ufc_fighter_id = (p->>'fighter_id')::uuid and identity_state = 'verified') <> 1 then
      raise exception 'drift: combat mirror for %', p->>'name'; end if;

    select to_jsonb(t) into before_row from public.ufc_fighters t where t.id = (p->>'fighter_id')::uuid;
    insert into public.ufc_identity_reconciliations (plan_sha256, kind, canonical_id, duplicate_id, evidence, before_images, operator)
    values ('f71b6f3f194a10016a7b9c9bdff1cb1807157e49859a891d0a3acbf0f42b2cb1', 'source_id_attach', (p->>'fighter_id')::uuid, null,
      jsonb_build_object('plan', PLAN_ID, 'name', p->>'name', 'espn_athlete_id', p->>'espn', 'espn_name', p->>'espn_name', 'ufcstats_id', p->>'ufcstats_id',
        'dob_evidence', jsonb_build_object('canonical', p->>'canonical_dob', 'espn', p->>'espn_dob', 'commission', p->>'commission_dob',
          'disputed', (p->>'espn_dob' is not null and p->>'espn_dob' is distinct from p->>'canonical_dob') or (p->>'commission_dob' is not null and p->>'commission_dob' is distinct from p->>'canonical_dob'),
          'action', 'canonical dob unchanged; a disagreement is recorded, not resolved by vote'),
        'anchor', jsonb_build_object('our_event', OUR_EVENT, 'bout_id', p->>'bout_id', 'role', p->>'role', 'opponent_id', p->>'opponent_id', 'espn_event', '400254173', 'espn_competition', p->>'competition'),
        'proof', 'the fighter''s bout on our finale event is reproduced by exactly one ESPN competition on the same event: winner/loser role, round and both printed names agree'),
      jsonb_build_object('ufc_fighters', before_row), 'scripts/reconcile/20260913_tuf2_espn_athlete_ids.sql');

    update public.ufc_fighters set espn_athlete_id = p->>'espn', updated_at = now() where id = (p->>'fighter_id')::uuid and espn_athlete_id is null;
    get diagnostics n = row_count;
    if n <> 1 then raise exception '% update % <> 1', p->>'name', n; end if;

    insert into public.combat_fighter_identities (combat_fighter_id, source_id, external_id, external_url, display_name, dob, verification_state, confidence, evidence)
    values ((p->>'combat_fighter_id')::uuid, ESPN_SOURCE, p->>'espn', 'https://www.espn.com/mma/fighter/_/id/' || (p->>'espn'), p->>'espn_name', (p->>'espn_dob')::date, 'verified', 100,
      jsonb_build_object('bridge', 'ufc_fighters.espn_athlete_id', 'ufc_fighter_id', p->>'fighter_id', 'reconciliation', PLAN_ID, 'espn_competition', p->>'competition', 'bout_id', p->>'bout_id'))
    returning id into new_id;
    new_ids := new_ids || new_id;

    select to_jsonb(t) into after_row from public.ufc_fighters t where t.id = (p->>'fighter_id')::uuid;
    if (after_row->>'espn_athlete_id') is distinct from p->>'espn' or (after_row->>'ufcstats_id') is distinct from p->>'ufcstats_id'
       or (after_row->>'dob') is distinct from (before_row->>'dob') or (after_row->>'name') is distinct from (before_row->>'name') then
      raise exception 'post: % changed beyond its ESPN id', p->>'name'; end if;
  end loop;

  select jsonb_build_object(
    'ufc_fighters',              (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_fighters t where t.id <> all(touched)),
    'ufc_fighters_touched_rest', (select jsonb_build_array(count(*), md5(coalesce(string_agg((to_jsonb(t) - 'espn_athlete_id' - 'updated_at')::text, '|' order by t.id), ''))) from public.ufc_fighters t where t.id = any(touched)),
    'ufc_bouts',                 (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_bouts t),
    'ufc_bout_results',          (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.bout_id), ''))) from public.ufc_bout_results t),
    'ufc_fighter_aliases',       (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_fighter_aliases t),
    'ufc_images',                (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_images t),
    'ufc_image_candidates',      (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_image_candidates t),
    'combat_fighters',           (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.combat_fighters t),
    'combat_fighter_identities', (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.combat_fighter_identities t where t.id <> all(new_ids)),
    'ufc_identity_reconciliations', (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_identity_reconciliations t where t.plan_sha256 <> 'f71b6f3f194a10016a7b9c9bdff1cb1807157e49859a891d0a3acbf0f42b2cb1')
  ) into fp_after;
  for k in select jsonb_object_keys(fp_before) loop
    if fp_before->k is distinct from fp_after->k then
      raise exception 'post: unrelated rows changed in % (before % after %)', k, fp_before->k, fp_after->k; end if;
  end loop;
  select count(*) into n from public.ufc_fighters where id = any(touched) and espn_athlete_id is not null;
  if n <> 10 then raise exception 'post: % of 10 fighters carry their ESPN id', n; end if;
  select count(*) into n from public.ufc_identity_reconciliations where plan_sha256 = 'f71b6f3f194a10016a7b9c9bdff1cb1807157e49859a891d0a3acbf0f42b2cb1';
  if n <> 10 then raise exception 'post: % audit rows', n; end if;
  if array_length(new_ids, 1) <> 10 then raise exception 'post: % combat ESPN identities', array_length(new_ids, 1); end if;

  if current_setting('reconcile.report', true) = 'raise' then
    raise exception 'PROOF OK: 10 fighters, 10 ESPN ids, 10 combat identities, 10 audit rows; unrelated fingerprints identical: %', fp_after;
  end if;
end
$attach$;

commit;
