-- TUF 1 contestants — attach ESPN athlete ids, 2026-09-13.
--
-- Approved for exactly these 16 fighters. Generated by
-- scripts/reconcile/tuf1_espn_athlete_ids.mjs from the plan in
-- scripts/reconcile/evidence/tuf1_espn_athlete_ids.2026-09-13.json (sha256 7ce08f76f44ec5ee08e203838d42289071ca06a7420ad3ddafedc61ba10a2af5).
--
-- Each mapping is anchored to one exact bout: the fighter's bout on our finale
-- event c93a5b04-6a74-4ec9-854b-422fbfbc5074 reproduced by one ESPN competition on ESPN event 400254386
-- (winner/loser role, round and both names agree). Nothing is merged, no DOB is
-- written to ufc_fighters, no UFC Stats id changes. Each fighter gains its ESPN id
-- and its combat mirror gains the ESPN identity row (with ESPN's printed DOB as
-- source evidence), and an audit row records the before-image.
--
-- FAIL CLOSED: exact pre-state is asserted per row; any ESPN id already held by
-- any canonical fighter aborts; every other row in the touched tables is
-- fingerprinted before and must be identical after; touched fighters may change
-- only espn_athlete_id and updated_at.
--
-- Proof, then apply:
--   pwsh scripts/db/apply_supabase_migration.ps1 -Mode proof -Chain -Paths "<source-attach migration>,scripts/reconcile/20260913_tuf1_espn_athlete_ids.sql"

begin;

do $attach$
declare
  PLAN constant text := 'tuf1-espn-athlete-ids-2026-09-13';
  ESPN_SOURCE constant uuid := 'cd71b196-8197-4df4-a806-26a78678d04b';
  EVENT constant uuid := 'c93a5b04-6a74-4ec9-854b-422fbfbc5074';
  plan_rows jsonb := '[
    {"fighter_id":"8b642ed0-b125-4945-b3d5-b8d07d950622","combat_fighter_id":"cd220b42-a480-4a97-a256-10adb5c395b4","name":"Bobby Southworth","ufcstats_id":"aee8eecfc4bfb1e7","espn":"2431311","espn_name":"Bobby Southworth","espn_dob":"1969-12-16","bout_id":"02aaa5ef-58f7-40ed-aa5c-5ad5bbe6b201","opponent_id":"190cb5c6-91eb-4f62-a4ce-1eae9c7c4550","role":"loser","competition":"156039"},
    {"fighter_id":"9dcc87e2-64f1-4ca7-91db-b2c72d3d5df1","combat_fighter_id":"dc1ac668-2a44-45dd-83de-fc3cad256634","name":"Josh Koscheck","ufcstats_id":"dd37fd509af89f15","espn":"2335664","espn_name":"Josh Koscheck","espn_dob":"1977-11-30","bout_id":"81d6e983-9257-46f0-8aa3-dbde10a9325f","opponent_id":"5876c5f7-eca1-4d00-bee4-e4d018134d56","role":"winner","competition":"153184"},
    {"fighter_id":"69133a27-6504-4af9-90c0-d8ea99568ef9","combat_fighter_id":"2108ce60-351a-4b21-b4b9-645fbb6fddb4","name":"Diego Sanchez","ufcstats_id":"82e7929bf6c2b689","espn":"2335671","espn_name":"Diego Sanchez","espn_dob":"1981-12-31","bout_id":"45c3c849-90b4-47ec-a891-76e7a1effa5f","opponent_id":"c709633d-c726-475e-8b5c-57eee382f8ba","role":"winner","competition":"152263"},
    {"fighter_id":"190cb5c6-91eb-4f62-a4ce-1eae9c7c4550","combat_fighter_id":"3700b25f-9eb3-45cb-a909-3588d97307bd","name":"Sam Hoger","ufcstats_id":"84a067c46306a737","espn":"2335605","espn_name":"Sam Hoger","espn_dob":"1980-06-28","bout_id":"02aaa5ef-58f7-40ed-aa5c-5ad5bbe6b201","opponent_id":"8b642ed0-b125-4945-b3d5-b8d07d950622","role":"winner","competition":"156039"},
    {"fighter_id":"a356d7e5-5b86-42c7-8794-5a2bc3b81c2d","combat_fighter_id":"a9bdcb91-d153-4fae-90d8-1a11d3a9b340","name":"Forrest Griffin","ufcstats_id":"fcffee71cff5530e","espn":"2335522","espn_name":"Forrest Griffin","espn_dob":"1979-07-01","bout_id":"65856c98-1421-4859-8e62-4eb651fdc221","opponent_id":"6fee988e-909c-47cd-9ef4-10e40c4e307c","role":"winner","competition":"152726"},
    {"fighter_id":"c709633d-c726-475e-8b5c-57eee382f8ba","combat_fighter_id":"d7b8181b-52c7-4dc0-8f48-d95e73452e87","name":"Kenny Florian","ufcstats_id":"cb139171ed1b69fe","espn":"2335675","espn_name":"Kenny Florian","espn_dob":"1976-05-26","bout_id":"45c3c849-90b4-47ec-a891-76e7a1effa5f","opponent_id":"69133a27-6504-4af9-90c0-d8ea99568ef9","role":"loser","competition":"152263"},
    {"fighter_id":"604ffb5b-aa8b-480e-bfd8-42d77fed28ed","combat_fighter_id":"8f651d1f-2d09-4dd6-beb4-c5c43b910d55","name":"Alex Schoenauer","ufcstats_id":"fdfef29ba17ee525","espn":"2335745","espn_name":"Alex Schoenauer","espn_dob":null,"bout_id":"2412c8e8-4689-4803-b0ac-0fae043c0835","opponent_id":"86d108cd-fdf9-4ba6-bd7a-e0572a2e10c0","role":"loser","competition":"152109"},
    {"fighter_id":"a4dd7ce2-b633-429b-adaf-a37b7cb7c46c","combat_fighter_id":"f30dd3b6-67c9-40dd-aa8f-6244e37717c7","name":"Josh Rafferty","ufcstats_id":"ff2c606c8bc365e3","espn":"2556812","espn_name":"Josh Rafferty","espn_dob":null,"bout_id":"5f1f4140-e151-4248-97c0-e801df49d90c","opponent_id":"f45ce067-f3a8-41d1-a889-1401d4fc35ac","role":"loser","competition":"156040"},
    {"fighter_id":"e8999544-0e72-4010-9d05-d4325b552f45","combat_fighter_id":"1820a9f5-4e5c-4376-b3cb-9c3b8a01d5e1","name":"Nate Quarry","ufcstats_id":"52cae54377b433b7","espn":"2335773","espn_name":"Nate Quarry","espn_dob":"1972-03-18","bout_id":"2edd40e1-3f39-4abd-a7c4-79876382a684","opponent_id":"20626c40-82a5-47f0-b8dd-3ed5d0fbfef9","role":"winner","competition":"153234"},
    {"fighter_id":"f5a4aee3-dd0a-4375-b1bc-0f5563d16590","combat_fighter_id":"0eb43d4f-bb18-482a-bd78-7b5dd6967e42","name":"Chris Leben","ufcstats_id":"d43a048a880efdff","espn":"2335513","espn_name":"Chris Leben","espn_dob":"1980-07-21","bout_id":"12a8d3f1-5289-44ed-b411-0a3bd0933b2a","opponent_id":"de37d9ab-7795-438e-b7fc-7479f9f4bbef","role":"winner","competition":"153494"},
    {"fighter_id":"6fee988e-909c-47cd-9ef4-10e40c4e307c","combat_fighter_id":"8557f3fb-e970-4fd7-b6dd-3115a3f81c45","name":"Stephan Bonnar","ufcstats_id":"c6a33ff198aaaeeb","espn":"2335525","espn_name":"Stephan Bonnar","espn_dob":"1977-04-04","bout_id":"65856c98-1421-4859-8e62-4eb651fdc221","opponent_id":"a356d7e5-5b86-42c7-8794-5a2bc3b81c2d","role":"loser","competition":"152726"},
    {"fighter_id":"86d108cd-fdf9-4ba6-bd7a-e0572a2e10c0","combat_fighter_id":"18a0393e-56e9-4381-b967-bf90cd000268","name":"Mike Swick","ufcstats_id":"9fe85152f351e737","espn":"2335819","espn_name":"Mike Swick","espn_dob":"1979-06-19","bout_id":"2412c8e8-4689-4803-b0ac-0fae043c0835","opponent_id":"604ffb5b-aa8b-480e-bfd8-42d77fed28ed","role":"winner","competition":"152109"},
    {"fighter_id":"20626c40-82a5-47f0-b8dd-3ed5d0fbfef9","combat_fighter_id":"36c6cad0-ec01-462d-8271-84d70205b479","name":"Lodune Sincaid","ufcstats_id":"265589bdd93e7ce5","espn":"2431312","espn_name":"Lodune Sincaid","espn_dob":null,"bout_id":"2edd40e1-3f39-4abd-a7c4-79876382a684","opponent_id":"e8999544-0e72-4010-9d05-d4325b552f45","role":"loser","competition":"153234"},
    {"fighter_id":"f45ce067-f3a8-41d1-a889-1401d4fc35ac","combat_fighter_id":"14cfed07-f75e-45cd-ae5c-d752d406e445","name":"Alex Karalexis","ufcstats_id":"e361e5c858af6ff1","espn":"2335822","espn_name":"Alex Karalexis","espn_dob":"1977-09-20","bout_id":"5f1f4140-e151-4248-97c0-e801df49d90c","opponent_id":"a4dd7ce2-b633-429b-adaf-a37b7cb7c46c","role":"winner","competition":"156040"},
    {"fighter_id":"5876c5f7-eca1-4d00-bee4-e4d018134d56","combat_fighter_id":"8d4b05e6-7b60-424b-a95f-16bd97591de3","name":"Chris Sanford","ufcstats_id":"29f935654825331b","espn":"2488455","espn_name":"Chris Sanford","espn_dob":null,"bout_id":"81d6e983-9257-46f0-8aa3-dbde10a9325f","opponent_id":"9dcc87e2-64f1-4ca7-91db-b2c72d3d5df1","role":"loser","competition":"153184"},
    {"fighter_id":"de37d9ab-7795-438e-b7fc-7479f9f4bbef","combat_fighter_id":"dc77ba9b-3ca4-4a39-8822-718ab7a163a0","name":"Jason Thacker","ufcstats_id":"f0264252e191da22","espn":"2431252","espn_name":"Jason Thacker","espn_dob":null,"bout_id":"12a8d3f1-5289-44ed-b411-0a3bd0933b2a","opponent_id":"f5a4aee3-dd0a-4375-b1bc-0f5563d16590","role":"loser","competition":"153494"}
  ]'::jsonb;
  touched uuid[];
  touched_combat uuid[];
  p jsonb; n bigint; fp_before jsonb; fp_after jsonb; k text; before_row jsonb; after_row jsonb; new_ids uuid[] := '{}'; new_id uuid;
begin
  select array_agg((x->>'fighter_id')::uuid), array_agg((x->>'combat_fighter_id')::uuid) into touched, touched_combat from jsonb_array_elements(plan_rows) x;
  if jsonb_array_length(plan_rows) <> 16 or (select count(distinct x->>'espn') from jsonb_array_elements(plan_rows) x) <> 16
     or (select count(distinct x->>'fighter_id') from jsonb_array_elements(plan_rows) x) <> 16 then
    raise exception 'plan: expected 16 distinct fighters and 16 distinct ESPN ids'; end if;
  /* No canonical fighter anywhere may already hold one of these ESPN ids. */
  select count(*) into n from public.ufc_fighters where espn_athlete_id in (select x->>'espn' from jsonb_array_elements(plan_rows) x);
  if n <> 0 then raise exception 'collision: % canonical fighter(s) already hold a planned ESPN id', n; end if;
  select count(*) into n from public.combat_fighter_identities where source_id = ESPN_SOURCE and external_id in (select x->>'espn' from jsonb_array_elements(plan_rows) x);
  if n <> 0 then raise exception 'collision: % combat ESPN identity row(s) already hold a planned ESPN id', n; end if;

  select jsonb_build_object(
    'ufc_fighters',              (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_fighters t where t.id <> all(touched)),
    'ufc_fighters_touched_rest', (select jsonb_build_array(count(*), md5(coalesce(string_agg((to_jsonb(t) - 'espn_athlete_id' - 'updated_at')::text, '|' order by t.id), ''))) from public.ufc_fighters t where t.id = any(touched)),
    'ufc_bouts',                 (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_bouts t),
    'ufc_bout_results',          (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.bout_id), ''))) from public.ufc_bout_results t),
    'ufc_fighter_aliases',       (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_fighter_aliases t),
    'ufc_images',                (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_images t),
    'ufc_image_candidates',      (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_image_candidates t),
    'combat_fighters',           (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.combat_fighters t),
    'combat_fighter_identities', (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.combat_fighter_identities t),
    'ufc_identity_reconciliations', (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_identity_reconciliations t)
  ) into fp_before;

  for p in select * from jsonb_array_elements(plan_rows) loop
    /* ---- exact pre-state ---- */
    if not exists (select 1 from public.ufc_fighters where id = (p->>'fighter_id')::uuid and name = p->>'name'
                     and ufcstats_id = p->>'ufcstats_id' and espn_athlete_id is null) then
      raise exception 'drift: % is not the planned canonical row (name, UFC Stats id, no ESPN id)', p->>'name'; end if;
    if not exists (select 1 from public.ufc_bouts b join public.ufc_bout_results r on r.bout_id = b.id
                     where b.id = (p->>'bout_id')::uuid and b.event_id = EVENT
                       and array[b.fighter_a_id, b.fighter_b_id] @> array[(p->>'fighter_id')::uuid, (p->>'opponent_id')::uuid]
                       and ((p->>'role' = 'winner' and r.winner_id = (p->>'fighter_id')::uuid) or (p->>'role' = 'loser' and r.winner_id = (p->>'opponent_id')::uuid))) then
      raise exception 'drift: % bout % is not the planned finale bout, opponent and result', p->>'name', p->>'bout_id'; end if;
    if (select count(*) from public.combat_fighters where id = (p->>'combat_fighter_id')::uuid and ufc_fighter_id = (p->>'fighter_id')::uuid and identity_state = 'verified') <> 1 then
      raise exception 'drift: combat mirror for %', p->>'name'; end if;

    select to_jsonb(t) into before_row from public.ufc_fighters t where t.id = (p->>'fighter_id')::uuid;
    insert into public.ufc_identity_reconciliations (plan_sha256, kind, canonical_id, duplicate_id, evidence, before_images, operator)
    values ('7ce08f76f44ec5ee08e203838d42289071ca06a7420ad3ddafedc61ba10a2af5', 'source_id_attach', (p->>'fighter_id')::uuid, null,
      jsonb_build_object('plan', PLAN, 'name', p->>'name', 'espn_athlete_id', p->>'espn', 'espn_name', p->>'espn_name', 'espn_dob', p->>'espn_dob',
        'ufcstats_id', p->>'ufcstats_id', 'anchor', jsonb_build_object('our_event', EVENT, 'bout_id', p->>'bout_id', 'role', p->>'role', 'opponent_id', p->>'opponent_id', 'espn_event', '400254386', 'espn_competition', p->>'competition'),
        'proof', 'the fighter''s bout on our finale event is reproduced by exactly one ESPN competition on the same event: winner/loser role, round and both printed names agree'),
      jsonb_build_object('ufc_fighters', before_row), 'scripts/reconcile/20260913_tuf1_espn_athlete_ids.sql');

    update public.ufc_fighters set espn_athlete_id = p->>'espn', updated_at = now() where id = (p->>'fighter_id')::uuid and espn_athlete_id is null;
    get diagnostics n = row_count;
    if n <> 1 then raise exception '% update % <> 1', p->>'name', n; end if;

    insert into public.combat_fighter_identities (combat_fighter_id, source_id, external_id, external_url, display_name, dob, verification_state, confidence, evidence)
    values ((p->>'combat_fighter_id')::uuid, ESPN_SOURCE, p->>'espn', 'https://www.espn.com/mma/fighter/_/id/' || (p->>'espn'), p->>'espn_name', (p->>'espn_dob')::date, 'verified', 100,
      jsonb_build_object('bridge', 'ufc_fighters.espn_athlete_id', 'ufc_fighter_id', p->>'fighter_id', 'reconciliation', PLAN, 'espn_competition', p->>'competition', 'bout_id', p->>'bout_id'))
    returning id into new_id;
    new_ids := new_ids || new_id;

    /* ---- post-state for the row ---- */
    select to_jsonb(t) into after_row from public.ufc_fighters t where t.id = (p->>'fighter_id')::uuid;
    if (after_row->>'espn_athlete_id') is distinct from p->>'espn' or (after_row->>'ufcstats_id') is distinct from p->>'ufcstats_id'
       or (after_row->>'dob') is distinct from (before_row->>'dob') or (after_row->>'name') is distinct from (before_row->>'name') then
      raise exception 'post: % changed beyond its ESPN id', p->>'name'; end if;
  end loop;

  select jsonb_build_object(
    'ufc_fighters',              (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_fighters t where t.id <> all(touched)),
    'ufc_fighters_touched_rest', (select jsonb_build_array(count(*), md5(coalesce(string_agg((to_jsonb(t) - 'espn_athlete_id' - 'updated_at')::text, '|' order by t.id), ''))) from public.ufc_fighters t where t.id = any(touched)),
    'ufc_bouts',                 (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_bouts t),
    'ufc_bout_results',          (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.bout_id), ''))) from public.ufc_bout_results t),
    'ufc_fighter_aliases',       (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_fighter_aliases t),
    'ufc_images',                (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_images t),
    'ufc_image_candidates',      (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_image_candidates t),
    'combat_fighters',           (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.combat_fighters t),
    'combat_fighter_identities', (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.combat_fighter_identities t where t.id <> all(new_ids)),
    'ufc_identity_reconciliations', (select jsonb_build_array(count(*), md5(coalesce(string_agg(t::text, '|' order by t.id), ''))) from public.ufc_identity_reconciliations t where t.plan_sha256 <> '7ce08f76f44ec5ee08e203838d42289071ca06a7420ad3ddafedc61ba10a2af5')
  ) into fp_after;
  for k in select jsonb_object_keys(fp_before) loop
    if fp_before->k is distinct from fp_after->k then
      raise exception 'post: unrelated rows changed in % (before % after %)', k, fp_before->k, fp_after->k; end if;
  end loop;
  select count(*) into n from public.ufc_fighters where id = any(touched) and espn_athlete_id is not null;
  if n <> 16 then raise exception 'post: % of 16 fighters carry their ESPN id', n; end if;
  select count(*) into n from public.ufc_identity_reconciliations where plan_sha256 = '7ce08f76f44ec5ee08e203838d42289071ca06a7420ad3ddafedc61ba10a2af5';
  if n <> 16 then raise exception 'post: % audit rows', n; end if;
  if array_length(new_ids, 1) <> 16 then raise exception 'post: % combat ESPN identities', array_length(new_ids, 1); end if;

  /* A proof run asks for the result as an exception so the rollback carries a report. */
  if current_setting('reconcile.report', true) = 'raise' then
    raise exception 'PROOF OK: 16 fighters, 16 ESPN ids, 16 combat identities, 16 audit rows; unrelated fingerprints identical: %', fp_after;
  end if;
end
$attach$;

commit;
